Core 1.6 change log
NHSDigital/NHSDigital-FHIR-BookingAndReferrals pull request #154
Opened 2024-05-16 10:28 UTC by Goslinl

2024-05-16 12:54 UTC, DylanHainsworthNHSD requested changes
Not sure about the use of the word "Current" as of 04/06 those will be obsolete. Can we call them "Original" or "Old" and call the above 2 "Latest" or "New" ?

2024-05-16 12:54 UTC, DylanHainsworthNHSD commented on guides/CopyofFHIRImplementationGuideTemplateTest/Home/Core/1.0.3/Security-and-Authorisation/Receiver.page.md
Not sure about the use of the word "Current" as of 04/06 those will be obsolete. Can we call them "Original" or "Old" and call the above 2 "Latest" or "New" ?

2024-05-16 14:03 UTC, julieharris37 commented on guides/CopyofFHIRImplementationGuideTemplateTest/Home/About-BaRS/Releases/Technical-Release-Notes/BaRS-Core/1.1.3.page.md
Documentation for BaRS Foundations - at the Hazard workshop DR said we should call it Standard Pattern for Appointment Management as it isn't BaRS specific. Is this still the right terminology?

2024-05-16 15:09 UTC, Goslinl commented on guides/CopyofFHIRImplementationGuideTemplateTest/Home/About-BaRS/Releases/Technical-Release-Notes/BaRS-Core/1.1.3.page.md
i can rename it to this, no problem

2024-05-17 08:24 UTC, Goslinl commented on guides/CopyofFHIRImplementationGuideTemplateTest/Home/Core/1.0.3/Security-and-Authorisation/Receiver.page.md
Old would indicate they are still okay, expired/deprecated explicitly defines their state. the top 2 are the old, the bottom two are the new.

2024-05-17 08:36 UTC, Goslinl commented on guides/CopyofFHIRImplementationGuideTemplateTest/Home/About-BaRS/Releases/Technical-Release-Notes/BaRS-Core/1.1.3.page.md
have updated all references to Foundation to Standard Pattern including documentation itself and core release notes.

2024-05-17 08:48 UTC, DylanHainsworthNHSD approved these changes

2024-05-17 09:00 UTC, Goslinl commented on guides/CopyofFHIRImplementationGuideTemplateTest/Home/Core/1.0.3/Security-and-Authorisation/Receiver.page.md
wasnt in 1.1.3 though! have added.

2024-05-17 11:07 UTC, merged